### ISSUE TITLE
Task list items with links don't render properly

### ISSUE THREAD

**Issue by ethanmdavidson** [Requarks/wiki#1226]
**Describe the bug**
When using the markdown editor, it is possible to create a task list by using the following syntax:

```markdown
- [x] Checked task item
- [x] Another checked task item
- [ ] Unchecked task item
```

However, if you try to put a link on an item:
```markdown
- [x] Checked task [item](http://www.google.com)
- [x] Another checked task item
- [ ] Unchecked task item
```
the item with the link becomes rendered like an unordered list item and the hyperlinked text becomes messed up (hyperlink still goes to correct URL).

**To Reproduce**
1. Enter the following markdown in any page:
```markdown
- [x] Checked task [item](http://www.google.com)
- [x] Another checked task item
- [ ] Unchecked task item
```

**Expected behavior**
Task list should still render checkboxes properly (i.e. show a checkbox instead of a unordered list bullet). Link should also be rendered properly (url should not be included in link text).

**Screenshots**
![image](https://user-images.githubusercontent.com/1311998/69092476-71a09c00-0a1a-11ea-836a-013f11e7bb46.png)

**Host Info (please complete the following information):**
 - OS: Linux - Centos (core) 7.7.1908 x64
 - Wiki.js version: 2.0.1
 - Database engine: Postgres 11.6

**Comment by fireundubh** [comment]
I can confirm that similar behavior occurs when using any kind of formatting, including HTML.

**Comment by timmyomahony** [comment]
I'm also experiencing this issue:

![](https://files.timmyomahony.com/Screenshot-2020-08-05-at-16.23.28-uVdd7W/Screenshot-2020-08-05-at-16.23.28.png)

**Comment by genesiscz** [comment]
Any updates on this?

**Comment by GuillaumeHullin** [comment]
@NGPixel unless I'm mistaken but latest version is 2.5.274 (which I'm running)... and I have this issue when rendering bold, inline code or else in a task list item.
It renders perfect in preview but not in final render.

PS: I just installed Wiki.js this week so maybe I missed something obvious

**Comment by GuillaumeHullin** [comment]
If you need more data, let me know but to reproduce, it's basically the same than #1860 which was referenced in this issue.

As a dirty workaround in order to get the bold formatting to work (the rest I don't use much), I inserted this in **Head HTML injection** via the Admin panel of Wiki.js

```html
<script type="text/javascript">
    window.addEventListener("load", function(){
        var render = document.getElementsByClassName("contents")[0];
        var lbl = render.getElementsByClassName("task-list-item-label");
        for (var i = 0; i < lbl.length; i++) {
            lbl[i].innerHTML = lbl[i].innerHTML.replace(/.*\*.+\*/,'');
        }
    });
</script>
```
