### ISSUE TITLE
Task list fails at formatting, links

### ISSUE THREAD

**Issue by Taffer** [Requarks/wiki#2761]
**Describe the bug**
Adding task list items with Markdown makes the editor preview and the rendered page go nuts.

**To Reproduce**
1. Create a new Markdown page or edit an existing one.
2. Add a task list of `- [ ] items`, all is well.
3. Add formatting, or links to any of the task items.
4. Behold the horrors!

**Expected behavior**
Task lists should work properly with additional formatting in them; they should be exactly like regular unordered list items, just with a checkbox.

**Screenshots**

In the editor, I have:

```markdown
Making a task list in Markdown with additional markup in it appears to go nuts:

- [ ] Here's an *Italic*.
- [ ] Here's a [link](https://www.isara.com/)
- [ ] This isn't quite right.

- [ ] What about **this**?
```

Which produces this in the preview:

![Screen Shot 2020-11-26 at 8 29 53 AM](https://user-images.githubusercontent.com/1213088/100357016-13f64680-2fc2-11eb-8fb5-3cd043dbd381.png)

And this in the rendered page:

![Screen Shot 2020-11-26 at 8 30 46 AM](https://user-images.githubusercontent.com/1213088/100357032-18bafa80-2fc2-11eb-8b0e-0fb408f4cbb8.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 20.04 LTS, node.js 10.19.0
 - Wiki.js version: 2.5.170
 - Database engine: PostgreSQL 12.5

**Comment by NGPixel** [comment]
Duplicate of #1226
