### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6541]
```[tasklist]
### Tasks
- [ ] Autocomplete
- [x] Filter By
- [x] Highlight Matches
- [x] Keyboard Shortcut Quick Access
- [x] Search Results Page
- [x] Sort By
- [x] Load Search Query from Query String
- [x] Tags Parsing In Query
```

### UI Prototype
<img width="1434" alt="image" src="https://github.com/requarks/wiki/assets/15522395/052ebf0b-0491-4bbc-a551-6a6865cfbdc9">

**Comment by NGPixel** [comment]
Autocomplete will be revisited in a future release, to properly address how to only serve terms from pages the user has access to.
