### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6542]
```[tasklist]
### Tasks
- [x] Tree Browse
- [x] Create Folder
- [x] Rename Folder
- [x] Duplicate Folder
- [x] Move Folder
- [x] Delete Folder
- [x] Upload Files
- [x] Search in Folder
- [x] Create Page from Current Path
- [x] Rename Page
- [x] Duplicate Page
- [x] Move Page
- [x] Delete Page
- [x] Rename Asset
- [x] Delete Asset
- [x] Move Asset
- [x] Delete Asset
- [x] Copy Page / Asset URL
- [x] Download Page
- [x] Download Asset
```
