### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6544]
```[tasklist]
### Tasks
- [x] Monaco Editor Engine
- [x] Real-time Preview
- [x] Scroll Sync
- [x] Formatting Controls
- [ ] Insert Link Dialog
- [x] Insert Asset
- [ ] Insert Code Block Dialog
- [ ] Insert Table Dialog
- [ ] Insert Tabset Dialog
- [ ] Insert Diagram Dialog
- [ ] Insert Footnote Dialog
- [ ] Insert Emoji Dialog
- [x] Insert Horizontal Bar
```
