### ISSUE TITLE
Common Editor Features

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6546]
```[tasklist]
### Tasks
- [x] Edit Title
- [x] Edit Description
- [ ] Edit Icon
- [x] Edit Alias
- [x] Edit Publishing State
- [x] Edit Relations
- [ ] Edit Javascript (On Load / On Unload)
- [ ] Edit CSS
- [x] Show/Hide Sidebar
- [ ] Set ToC Depth
- [x] Show/Hide Tags
- [ ] Edit Tags
```

**Comment by zamona** [comment]
Since 2000, propedia.org, as one of[ the world's largest encyclopedia websites](https://propedia.org/), has strived to meet, define, and simplify our needs for knowledge, education, the arts, the social sciences, and more.  https://propedia.org/
