### ISSUE TITLE
Approval Workflow

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6556]
### Objective

Provide a workflow where users can submit new pages / edits to an existing page and have authorized users review and approve them.

> Note that this feature is planned for 3.1 or later release.

```[tasklist]
### Tasks
- [ ] Admin page to define paths that require approval and from who
- [ ] Allow users with read access to submit an edit / new page for review (contributions)
- [ ] Allow multiple users to approve a workflow (with min. approvals option)
- [ ] Page contribution review screen
- [ ] View contributions for the current page
- [ ] Approval status display on contribution
- [ ] Notification area where users can see the page contributions awaiting review
```

**Comment by pixlcrashr** [comment]
I really look forward for this!😄

**Comment by eangulus** [comment]
Currently hunting for an internal WIki for a business.

Did this feature ever come about?

As far as I can find so far, Wiki.js would be at the top of my list, if it wasn't for this feature being missing.

**Comment by bitsondatadev** [comment]
@eangulus, this project is incredible but not structured in a way that moves very quickly. Notice [the slow cadence of development](https://github.com/requarks/wiki/commits/main/).

There's nothing wrong with this as @NGPixel has a very opinionated development style and this keeps the quality of the codebase cleaner, but also can stagnate projects. It kind of comes down to devs wanting to develop features at their own pace versus managing a bunch of issues and other developers working on their project instead of coding. 

The unfortunate thing is that this puts people who want these features sooner in a bit of a bind as there's no way of knowing when this will become a priority. This feature is something I'd really like to dig into at some point but don't currently have the time. If anyone is interested in setting up a fork to get this feature working as a temporary workaround (possibly a rough draft for maintainers) then I'd be game to help out in any way I can.

Here's some relevant discussions on this: https://github.com/requarks/wiki/discussions/5614

CC: @timsamart and @MarcBollmann

**Comment by pixlcrashr** [comment]
I am still looking forward to this!😄
