### ISSUE TITLE
Audit Log

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6557]
### Objective

Keep a log of every action by all users. This should include both page editing and management actions.

> Note that this feature is planned for 3.1 or later release.

```[tasklist]
### Tasks
- [x] Pages - Prompt the user to enter a short description for an edit. (optional enforcement)
- [x] Pages - Log which fields were changed during an edit.
- [x] Pages - Log page actions (such as delete, move, rename, etc.)
- [x] Pages - View history of a page
- [x] Admin - Log all management actions.
- [x] Admin - Page to view the history of all actions by a user, or by timeframe.
- [x] Admin - Ability to purge the history (with timeframe options), only by the administrator group. A flag could be set via the config.yml or ENV var to disable this ability altogether.
```

Related to #6558
