### ISSUE TITLE
Page History

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6558]
### Objective

Provide the history of changes made to a page, view differences and allow to revert to a previous version.

```[tasklist]
### Tasks
- [ ] Store previous versions of a page on edit
- [ ] View a list of previous versions of a page
- [ ] Compare between 2 versions (diff view)
- [ ] View the rendered view of a previous version
- [ ] Download a specific version
- [ ] Revert to a previous version
```

Related to #6557

**Comment by openbrian** [comment]
I'm using version 2.5.292.  Seems like some of these tasks are completed.  I'm not sure if you're storing previous versions of pages, or just the deltas.  But these seem done:

* View a list of previous versions of a page.
* Compare between 2 versions (very nicely done btw)

I came here searching for "revert to a previous version".  Looking forward to that.

**Comment by NGPixel** [comment]
@openbrian This issue is for v3, not the 2.x branch.

You can already revert to a previous version in 2.x.

**Comment by paul-hammant** [comment]
If you search for "history" on https://docs.requarks.io/ you don't find the fact that it's partially done - as indicated above https://github.com/requarks/wiki/issues/6558#issuecomment-1708349700
