### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6591]
### Objective

A customizable and intuitive login and registration experience for users.

```[tasklist]
### Tasks
- [x] Login Page
- [x] Login
- [ ] 3rd Party Authentication
- [x] Register
- [x] 2FA Registration
- [x] 2FA Login
- [x] Change Password on Login
- [ ] Forgot Password
- [x] Change Own Password
- [x] Deactivate 2FA
- [x] Enroll 2FA
- [x] Enroll Passkeys
- [x] Delete Passkeys
- [x] Login with Passkeys
```

**Comment by ssy2306** [comment]
Interested to solve for registration #6591

**Comment by metaben** [comment]
Would it be possible to add more logging coverage for planned and implemented Authentication functionality please?
