### ISSUE TITLE
Use Iconify to load icons

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6692]
### Objective

Use Iconify to load icons via on-demand SVG rather than using webfonts.

```[tasklist]
### Tasks
- [ ] Implement Iconify Vue component
- [ ] Add local copy of Iconify resources
- [ ] Admin page to control packages to allow / APIs to use
```

**Comment by ajukadavid** [comment]
@NGPixel can i work on this issue?

**Comment by An-Borsen** [comment]
Will this issue be worked on?

**Comment by ub-victor** [comment]
I'd like to work on this, @NGPixel @ajukadavid @An-Borsen  , I can see no PR has been raised to address and close this issue #6692
Can I work on it !
