### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by NGPixel** [requarks/wiki#6801]
### Objective

Ability to send emails based on trigger events.

```[tasklist]
### Tasks
- [x] Send Test Email
- [x] Send User Welcome Email
- [ ] Send User Verify Email
- [ ] Handle multilingual content
- [ ] Mail Templates Editor
```

Related to #6557

**Comment by ub-victor** [comment]
This issue has not yet been addressed since 2023. Please assign it to me so I can submit a PR by the end of this week. Mr @NGPixel
